# Error is shown because the method def cant access a outside the method's scope

a = 7

def my_value(b)
  b = a + a
end

my_value(a)
puts a